
environment:
  matrix:
  # 32/64 bit MSVC builds.
  - CHANNEL: nightly
    TARGET: x86_64-pc-windows-msvc
  - CHANNEL: nightly
    TARGET: i686-pc-windows-msvc

  # 32/64-bit MinGW builds.
  - CHANNEL: nightly
    TARGET: x86_64-pc-windows-gnu
  - CHANNEL: nightly
    TARGET: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

clone_depth: 1

build: false

test_script:
  - cargo build --target %TARGET%
  - cd workshopper
  - cargo test
  - cd ..
  - cargo test
  - cargo build --target %TARGET% --release

cache:
  - target
  - C:\Users\appveyor\.cargo\registry