---
dist: trusty
language: rust
sudo: false
git:
  depth: 5

rust: stable

cache:
  cargo: true

before_script:
  - '
    git config user.name "Deployment Bot (from Travis CI)" &&
    git config user.email "deploy@travis-ci.org"
    '
script:
  '
  echo "missing Travis script !" &&
  exit 1
  '

jobs:
  include:

    #

    - stage: Test
    #
      rust: stable
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
      deploy:
    -
      rust: beta
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
      deploy:
    -
      rust: nightly
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
      deploy:

    #

    - stage: Build
    #
      env: TARGET=i686-apple-darwin
      os: osx
      before_script: 'rustup target add $TARGET'
      script: sh ./.travis/build.sh $TARGET
    -
      addons:
        apt:
          packages:
            # Solve missing ncurses5, ncursesw5
            - lib32ncurses5-dev
            - lib32ncursesw5-dev
            # Solve fatal error: sys/cdefs.h: No such file or directory
            - libc6-dev-i386
            - libx32gcc-4.8-dev
            # Solve incompatible gcc versions
            - gcc-multilib 
            - g++-multilib
      env: TARGET=i686-unknown-linux-gnu
      before_script: 'rustup target add $TARGET'
      script: sh ./.travis/build.sh $TARGET
    -
      env: TARGET=x86_64-apple-darwin
      os: osx
      script: sh ./.travis/build.sh $TARGET
    -
      env: TARGET=x86_64-unknown-linux-gnu
      script: sh ./.travis/build.sh $TARGET

    #

  fast_finish: true

before_deploy:
  - export RELEASE_FILE=$(ls $TRAVIS_BUILD_DIR/releases/*)
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $RELEASE_FILE
  skip_cleanup: true
  on:
    tags: true
