---
dist: trusty
language: rust
sudo: false
git:
  depth: 5

rust: stable

cache:
  cargo: true

script:
  '
  echo "missing Travis script !" &&
  exit 1
  '

jobs:
  include:

    #

    - stage: Test
    #
      rust: stable
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
    -
      rust: beta
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
    -
      rust: nightly
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh

    #

    - stage: Build
    #
      env: TARGET=i686-apple-darwin
      os: osx
      before_script: 'rustup target add $TARGET'
      script: cargo build --target $TARGET --release --verbose
    -
      addons:
        apt:
          packages:
            # Solve missing ncurses5, ncursesw5
            - lib32ncurses5-dev
            - lib32ncursesw5-dev
            # Solve fatal error: sys/cdefs.h: No such file or directory
            - libc6-dev-i386
            - libx32gcc-4.8-dev
            # Solve incompatible gcc versions
            - gcc-multilib 
            - g++-multilib
      env: TARGET=i686-unknown-linux-gnu
      before_script: 'rustup target add $TARGET'
      script: cargo build --target $TARGET --release --verbose
    -
      env: TARGET=x86_64-apple-darwin
      os: osx
      script: cargo build --target $TARGET --release --verbose
    -
      env: TARGET=x86_64-unknown-linux-gnu
      script: cargo build --target $TARGET --release --verbose

    #

  fast_finish: true
