---
dist: trusty
language: rust
sudo: false
git:
  depth: 5

rust: stable

cache:
  apt: true
  cargo: true

addons:
  apt:
    packages:
    - libncursesw5-dev

before_script: 'cargo build'

script:
  '
  echo "missing Travis script !" &&
  exit 1
  '

jobs:
  include:

    #

    - stage: Test
    #
      rust: stable
      script: sh ./.travis/test.sh
    -
      rust: beta
      script: sh ./.travis/test.sh
    -
      rust: nightly
      script: sh ./.travis/test.sh

    #

    - stage: Build
    #
      env: TARGET=i686-apple-darwin
      os: osx
      before_script: 'rustup target add $TARGET'
      script: *build
    -
      env: TARGET=i686-unknown-linux-gnu
      before_script: 'rustup target add $TARGET'
      script: *build
    -
      env: TARGET=x86_64-apple-darwin
      os: osx
      script: *build
    -
      env: TARGET=x86_64-unknown-linux-gnu
      script: *build

    #

  fast_finish: true

aliases:
  - &build 'cargo build --target $TARGET; cargo build --target $TARGET --release'