---
dist: trusty
language: rust
sudo: false
git:
  depth: 5

rust: stable

cache: cargo

before_script: 'cargo build'

script:
  '
  cd workshopper && cargo test && cd - &&
  cargo test
  '

jobs:
  include:

    #

    - stage: Test
      rust: stable
    -
      rust: beta
    -
      rust: nightly

    #

  fast_finish: true
