---
dist: trusty
language: rust
sudo: false
git:
  depth: 5

rust: stable

cache:
  cargo: true

before_script: sh -xc "
  git config user.name "Deployment Bot (from Travis CI)"
  git config user.email "deploy@travis-ci.org"
;"
script: sh -xc "
  echo "missing Travis script !"
  exit 1
;"

jobs:
  include:

    #

    - stage: Test
    #
      rust: stable
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
      deploy:
    -
      rust: beta
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
      deploy:
    -
      rust: nightly
      before_script: cargo build --verbose
      script: sh ./.travis/test.sh
      deploy:

    #

    - stage: Build
    #
      env: TARGET=i686-apple-darwin
      os: osx
      before_script: 'rustup target add $TARGET'
      script: cargo build --target $TARGET --release --verbose
    -
      addons:
        apt:
          packages:
            # Solve missing ncurses5, ncursesw5
            - lib32ncurses5-dev
            - lib32ncursesw5-dev
            # Solve fatal error: sys/cdefs.h: No such file or directory
            - libc6-dev-i386
            - libx32gcc-4.8-dev
            # Solve incompatible gcc versions
            - gcc-multilib 
            - g++-multilib
      env: TARGET=i686-unknown-linux-gnu
      before_script: 'rustup target add $TARGET'
      script: cargo build --target $TARGET --release --verbose
    -
      env: TARGET=x86_64-apple-darwin
      os: osx
      script: cargo build --target $TARGET --release --verbose
    -
      env: TARGET=x86_64-unknown-linux-gnu
      script: cargo build --target $TARGET --release --verbose

    #

  fast_finish: true

before_deploy: sh -xc "
  export name="learnrust-$TRAVIS_TAG-stable-$TARGET"
  mkdir $name
  cp target/$TARGET/release/learnrust $name/
  cp README.md LICENSE $name/
  tar Jcvf $name.tar.xz $name
;"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $name
  skip_cleanup: true
  on:
    tags: true
