
environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    OTHER_TARGET: i686-pc-windows-msvc
    MAKE_TARGETS: test-unit-x86_64-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
    OTHER_TARGET: i686-pc-windows-gnu
    MAKE_TARGETS: test-unit-x86_64-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup target add %OTHER_TARGET%
  - rustc -V
  - cargo -V
  - git submodule update --init

clone_depth: 1

build: false

test_script:
  - cargo test
  - cargo build --target %TARGET%
  - cargo build --target %TARGET% --release
