
environment:
  matrix:
  # 32/64 bit MSVC tests
  - MSYS_BITS: 64
    TARGET: x86_64-pc-windows-msvc
  - MSYS_BITS: 32
    TARGET: i686-pc-windows-msvc

  # 32/64-bit MinGW builds.
  - MSYS_BITS: 64
    TARGET: x86_64-pc-windows-gnu
  - MSYS_BITS: 32
    TARGET: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

clone_depth: 1

build: false

test_script:
  - cargo build --target %TARGET%
  - cargo test
  - cargo build --target %TARGET% --release